"""Code map: xval_select_holdout_set — propensity-balanced holdout-set generator."""

from codemap_lib import Slide


def build() -> Slide:
    s = Slide(
        title="CANlab code map: xval_select_holdout_set",
        description=[
            "Construct cross-validation holdout sets that are balanced on outcome Y and a set of nuisance covariates,",
            "inspired by Rubin's propensity-score idea — reduces variance in cross-validated accuracy estimates.",
        ],
    )

    s.use([
        "Pass the outcome vector Y, a covariate matrix, the desired number of folds, and the holdout proportion in [0, 1].",
        "Returns a [obs × nfolds] indicator matrix — 1 means that observation is in that fold's holdout.",
        "Useful for inner CV in nested cross-validation, where balanced holdouts give stable inner-loop estimates.",
    ])

    s.notes([
        "Each fold is generated by an iterative resampling that minimizes the dependence between holdout assignment and the covariates.",
        "Pass doplot = 1 (4th positional argument) for a balance-diagnostic figure across folds.",
    ], y=3.40, h=1.50)

    s.legend(x=0.30, y=5.30)

    spine_x = 5.10
    y0 = 1.20
    gap = 0.85
    s.spine([
        ("Y", "var", "Y (outcome)"),
        ("xv", "func", "xval_select_holdout_set( )"),
        ("gen", "func", "generate_balanced_sets\n(propensity sampling)"),
        ("repair", "func", "ensure all obs sampled\n(missing-fold repair loop)"),
        ("out", "var", "wh_holdout_final\n[obs × nfolds]"),
    ], x=spine_x, y0=y0, row_gap=gap, box_h=0.62, bold_ids=["xv"])

    # Other inputs
    rx = spine_x + 2.60
    s.box("covs", "var", "covs\n[obs × p]", x=rx, y=y0, h=0.65)
    s.box("nfolds", "var", "nfolds", x=rx, y=y0 + 0.85, h=0.65)
    s.box("prop", "var", "holdout_proportion\n∈ [0, 1]", x=rx, y=y0 + 1.70, h=0.65)
    for nid in ("covs", "nfolds", "prop"):
        s.connect_line(nid, "xv", src_side="left", dst_side="right")

    # Plot side-effect
    s.box("plot", "script", "balance diagnostic\n(if doplot)",
          x=spine_x - 2.80, y=y0 + 2 * gap, h=0.65, w=2.30, font_size=10.0)
    s.connect_line("xv", "plot", src_side="left", dst_side="right")

    s.object_types_panel(
        x=rx, y=y0 + 2.55,
        lines=["numeric matrix"],
        width=2.10,
    )
    return s
